# Generated by Django 4.2.5 on 2023-09-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='image',
            field=models.ImageField(default=1, upload_to='rooms'),
            preserve_default=False,
        ),
    ]
