# Generated by Django 4.2.5 on 2023-09-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_manga_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(upload_to='media/rooms'),
        ),
    ]
