# Generated by Django 4.2.5 on 2023-09-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_alter_manga_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
    ]
